# Site settings
title: 
email: 
phone: 
phone-link: 0
description: > 
  
baseurl: "/"
url: ""
twitter_username: 
facebook_username: 

# Build settings
markdown: kramdown

# Angular Plugin
gems:
  - jekyll-angular
  - bourbon
